# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
    -   id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        types_or: [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []
    -   id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi]
        args: [--check]
        require_serial: true
        additional_dependencies: []

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        name: mypy
        description: "Run 'mypy' for Python linting"
        entry: mypy
        language: python
        args: [--strict, --ignore-missing-imports]
        require_serial: true
        additional_dependencies: []

-   repo: local
    hooks:
        - id: commitlint
          name: commitlint
          entry: pnpm commitlint --edit
          language: system
          stages: [commit-msg]
        - id: check-branch-name
          name: check-branch-name
          entry: scripts/hooks/check-branch-name.sh
          language: system
          stages: [pre-push]
          pass_filenames: false
